import { Trip, Poll, User, ForumPost, GalleryItem, Booking } from '@/types';

export const mountains: Trip['mountain'][] = [
  {
    id: 'rinjani',
    name: 'Gunung Rinjani',
    location: 'Lombok, NTB',
    province: 'Nusa Tenggara Barat',
    elevation: 3726,
    description: 'Gunung Rinjani adalah gunung api terbesar di Lombok dengan caldera yang indah dan Danau Segara Anak di puncaknya.',
    image: 'https://images.unsplash.com/photo-1605648916361-9bc12ad6a569?w=800',
  },
  {
    id: 'semeru',
    name: 'Gunung Semeru',
    location: 'Lumajang, Jawa Timur',
    province: 'Jawa Timur',
    elevation: 3676,
    description: 'Gunung Semeru adalah gunung tertinggi di Pulau Jawa dengan pemandangan sunrise yang spektakuler dari Ranu Kumbolo.',
    image: 'https://images.unsplash.com/photo-1583791196566-primer-photo?w=800',
  },
  {
    id: 'merbabu',
    name: 'Gunung Merbabu',
    location: 'Boyolali, Jawa Tengah',
    province: 'Jawa Tengah',
    elevation: 3145,
    description: 'Gunung Merbabu dikenal dengan padang savana yang luas dan terkenal sebagai gunung untuk pemula.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800',
  },
  {
    id: 'bromo',
    name: 'Gunung Bromo',
    location: 'Probolinggo, Jawa Timur',
    province: 'Jawa Timur',
    elevation: 2329,
    description: 'Gunung Bromo menawarkan pemandangan matahari terbit yang ikonik di atas lautan pasir dengan kawah aktif.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
  },
  {
    id: 'merapi',
    name: 'Gunung Merapi',
    location: 'Yogyakarta, DIY',
    province: 'Yogyakarta',
    elevation: 2968,
    description: 'Gunung Merapi adalah gunung berapi paling aktif di Indonesia dengan jalur pendakian yang menantang.',
    image: 'https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=800',
  },
  {
    id: 'sumbing',
    name: 'Gunung Sumbing',
    location: 'Magelang, Jawa Tengah',
    province: 'Jawa Tengah',
    elevation: 3371,
    description: 'Gunung Sumbing adalah gunung dengan bentuk kerucut sempurna dan menjadi favorit pendaki.',
    image: 'https://images.unsplash.com/photo-1585146416406-a0b9dd4e3bb9?w=800',
  },
  {
    id: 'lauser',
    name: 'Gunung Lawu',
    location: 'Karanganyar, Jawa Tengah',
    province: 'Jawa Tengah',
    elevation: 3265,
    description: 'Gunung Lawu terletak di perbatasan Jawa Tengah dan Jawa Timur dengan suasana yang mistis.',
    image: 'https://images.unsplash.com/photo-1526779259212-939e64788e3c?w=800',
  },
  {
    id: 'argopuro',
    name: 'Gunung Argopuro',
    location: 'Banyuwangi, Jawa Timur',
    province: 'Jawa Timur',
    elevation: 3088,
    description: 'Gunung Argopuro memiliki jalur pendakian terpanjang di Jawa dengan pemandangan savana yang luas.',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
  },
];

export const trips: Trip[] = [
  {
    id: 'rinjani-3d2n',
    mountain: mountains[0],
    title: 'Expedisi Rinjani 3D2N - Via Sembalun',
    description: 'Nikmati pendakian ke puncak tertinggi di Lombok dengan pemandangan caldera yang memukau dan sunrise spektakuler di puncak.',
    duration: 3,
    difficulty: 'Hard',
    price: 2850000,
    maxParticipants: 15,
    currentParticipants: 8,
    departureDates: ['2026-04-15', '2026-04-22', '2026-05-01', '2026-05-10'],
    itinerary: [
      {
        day: 1,
        title: 'Hari 1: Start Point - Plawangan Sembalun',
        activities: [
          'Registrasi dan briefing di Basecamp Sembalun (07:00)',
          'Persiapan perlengkapan hiking',
          'Start pendakian (08:00)',
          'Tiba di Plawangan Sembalun (12:00)',
          'Istirahat dan makan siang',
          'Pendakian menuju Summit (22:00)',
        ],
        accommodation: 'Tenda di Plawangan',
        meals: ['Makan siang', 'Makan malam', 'Snack'],
      },
      {
        day: 2,
        title: 'Hari 2: Puncak - Danau Segara Anak - Plawangan',
        activities: [
          'Tiba di Puncak Rinjani (03:00)',
          'Nikmati sunrise dari puncak',
          'Foto-foto dan istirahat',
          'Turun menuju Danau Segara Anak',
          'Mandi di pemandian air panas',
          'Kembali ke Plawangan',
        ],
        accommodation: 'Tenda di Plawangan',
        meals: ['Sarapan', 'Makan siang', 'Makan malam', 'Snack'],
      },
      {
        day: 3,
        title: 'Hari 3: Plawangan - Basecamp',
        activities: [
          'Sarapan pagi',
          'Packing perlengkapan',
          'Turun ke Basecamp Sembalun',
          'Tiba di Basecamp (11:00)',
          'Mandi dan bersih-bersih',
          'Penjemputan ke Mataram/Lombok Airport',
        ],
        meals: ['Sarapan', 'Makan siang'],
      },
    ],
    includes: [
      'Transportasi PP Lombok Airport - Basecamp',
      'Akomodasi tenda (2 malam)',
      'Makanan selama pendakian',
      'Guide bersertifikat',
      'Porter untuk perlengkapan bersama',
      'Tiket masuk TN Rinjani',
      'Asuransi kecelakaan',
      'Alat memasak dan kompor gas',
      'Tenda, sleeping bag, matras',
    ],
    excludes: [
      'Transportasi ke Lombok',
      'Makanan di luar jadwal',
      'Personal expenses',
      'Tip guide dan porter',
      'Sleeping bag personal',
    ],
    whatToBring: [
      'Sepatu hiking anti slip',
      'Jaket windbreaker/pelindung hujan',
      'Senter/headlamp',
      'Botrek/stocking kaki',
      'Tas carrier (50-70L)',
      'Air minum (2L minimum)',
      'Obat-obatan pribadi',
      'Kamera/action cam',
      'Powerbank',
      'Sunblock & lip balm',
    ],
    images: [
      'https://images.unsplash.com/photo-1605648916361-9bc12ad6a569?w=800',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
      'https://images.unsplash.com/photo-1526779259212-939e64788e3c?w=800',
    ],
    reviews: [
      {
        id: 'rev1',
        userId: 'user1',
        userName: 'Budi Santoso',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
        rating: 5,
        comment: 'Pengalaman yang luar biasa! Guide sangat profesional dan pemandangan di puncak tidak terlukiskan.',
        date: '2026-03-15',
        tripDate: '2026-03-10',
      },
      {
        id: 'rev2',
        userId: 'user2',
        userName: 'Ani Wijaya',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
        rating: 5,
        comment: 'Organisasi trip sangat bagus, makanannya enak-enak. Highly recommended!',
        date: '2026-03-08',
        tripDate: '2026-03-05',
      },
    ],
    location: 'Sembalun, Lombok, NTB',
    elevationGain: 1900,
    terrainType: ['Savana', 'Hutan', 'Bebatuan', 'Puncak'],
  },
  {
    id: 'semeru-4d3n',
    mountain: mountains[1],
    title: 'Pendakian Semeru 4D3N - Ranu Kumbolo Adventure',
    description: 'Raih puncak tertinggi di Pulau Jawa dengan keindahan Ranu Kumbolo sebagai destinasi utama. Pengalaman tak terlupakan!',
    duration: 4,
    difficulty: 'Hard',
    price: 3200000,
    maxParticipants: 12,
    currentParticipants: 6,
    departureDates: ['2026-04-18', '2026-05-03', '2026-05-15'],
    itinerary: [
      {
        day: 1,
        title: 'Hari 1: Ranu Kumbolo',
        activities: [
          'Registrasi di Basecamp Tower (06:00)',
          'Start pendakian (07:00)',
          'Jalur melalui Oro-oro Ombo',
          'Tiba di Ranu Kumbolo (14:00)',
          'Camp dan istirahat',
          'Menikmati sunset di danau',
        ],
        accommodation: 'Tenda di Ranu Kumbolo',
        meals: ['Makan siang', 'Makan malam', 'Snack'],
      },
      {
        day: 2,
        title: 'Hari 2: Oro-oro Ombo - Summit Attempt',
        activities: [
          'Start menuju Oro-oro Ombo (00:00)',
          'Naik ke Mahameru (04:00)',
          'Nikmati sunrise dari puncak',
          'Turun kembali ke Ranu Kumbolo',
          'Istirahat dan recovery',
        ],
        accommodation: 'Tenda di Ranu Kumbolo',
        meals: ['Sarapan', 'Makan siang', 'Makan malam', 'Snack'],
      },
      {
        day: 3,
        title: 'Hari 3: Ranu Kumbolo Exploration',
        activities: [
          'Pagi hari di sekitar danau',
          'Jalur alternative Cemara Kokok',
          'Fotografi dan eksplorasi',
          'Persiapan turun',
        ],
        accommodation: 'Tenda di Ranu Kumbolo',
        meals: ['Sarapan', 'Makan siang', 'Makan malam'],
      },
      {
        day: 4,
        title: 'Hari 4: Turun ke Basecamp',
        activities: [
          'Packing dan sarapan',
          'Turun via Jalur Ranu Kumbolo',
          'Tiba di Basecamp (12:00)',
          'Transfer ke kota',
        ],
        meals: ['Sarapan', 'Makan siang'],
      },
    ],
    includes: [
      'Transportasi dari Malang/Lumajang',
      'Akomodasi tenda (3 malam)',
      'Makanan lengkap',
      'Guide berpengalaman',
      'Porter untuk gear bersama',
      'Tiket masuk TN Bromo Tengger Semeru',
      'Asuransi kecelakaan',
      'Peralatan camping',
    ],
    excludes: [
      'Transportasi ke Malang',
      'Personal expenses',
      'Tip untuk guide & porter',
      'Makanan di luar jadwal',
    ],
    whatToBring: [
      'Sepatu hiking water-resistant',
      'Jas hujan',
      'Headlamp dengan spare baterai',
      'Botrek panjang',
      'Tas carrier 60-70L',
      'Botol minum 2L',
      'Obat anti mabuk',
      'Kamera underwater case',
    ],
    images: [
      'https://images.unsplash.com/photo-1583791196566-primer-photo?w=800',
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    ],
    reviews: [
      {
        id: 'rev3',
        userId: 'user3',
        userName: 'Dewi Rahmawati',
        userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
        rating: 4,
        comment: 'Trip yang seru! Butuh perjuangan ekstra untuk mencapai puncak tapi worth it banget.',
        date: '2026-03-01',
        tripDate: '2026-02-25',
      },
    ],
    location: 'Taman Nasional Bromo Tengger Semeru, Jawa Timur',
    elevationGain: 2100,
    terrainType: ['Hutan pinus', 'Savana', 'Pantai pasir', 'Bebatuan'],
  },
  {
    id: 'merbabu-2d1n',
    mountain: mountains[2],
    title: 'Merbabu Starter Pack - 2D1N Campinjani',
    description: 'Pilihan sempurna untuk pemula yang ingin merasakan pengalaman mendaki gunung. Via Campinjani dengan pemandangan savana yang indah.',
    duration: 2,
    difficulty: 'Moderate',
    price: 1250000,
    maxParticipants: 20,
    currentParticipants: 14,
    departureDates: ['2026-04-12', '2026-04-19', '2026-04-26', '2026-05-03', '2026-05-09'],
    itinerary: [
      {
        day: 1,
        title: 'Hari 1: Basecamp - Theo Peak Camp',
        activities: [
          'Registrasi di Basecamp Campinjani (08:00)',
          'Briefing dan pembagian logistik',
          'Start pendakian (09:00)',
          'Jalur via Wekas',
          'Tiba di Theo Peak Camp (13:00)',
          'Istirahat dan menikmati sunset',
        ],
        accommodation: 'Tenda di Theo Peak Camp',
        meals: ['Makan siang', 'Makan malam', 'Snack'],
      },
      {
        day: 2,
        title: 'Hari 2: Summit Attempt - Basecamp',
        activities: [
          'Start summit attempt (03:00)',
          'Tiba di puncak (05:30)',
          'Nikmati sunrise dan pemandangan',
          'Turun ke camp dan istirahat',
          'Packing dan turun ke basecamp',
          'Tiba di basecamp (11:00)',
        ],
        meals: ['Sarapan', 'Makan siang'],
      },
    ],
    includes: [
      'Transportasi dari Yogyakarta/Solo',
      'Akomodasi tenda (1 malam)',
      'Makanan selama trip',
      'Guide bersertifikat',
      'Tiket masuk',
      'Asuransi kecelakaan',
      'Peralatan camping dasar',
    ],
    excludes: [
      'Transportasi ke basecamp',
      'Personal expenses',
      'Tip guide',
    ],
    whatToBring: [
      'Sepatu hiking',
      'Jaket tipis',
      'Headlamp',
      'Botrek',
      'Tas carrier 40-50L',
      'Air minum 1.5L',
      'Sarung tangan',
    ],
    images: [
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
    ],
    reviews: [
      {
        id: 'rev4',
        userId: 'user4',
        userName: 'Rizky Pratama',
        userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
        rating: 5,
        comment: 'First time hiking dan觉得这 cocok banget untuk pemula. Guidenya sabar dan helpful!',
        date: '2026-03-20',
        tripDate: '2026-03-18',
      },
    ],
    location: 'Campinjani, Boyolali, Jawa Tengah',
    elevationGain: 1200,
    terrainType: ['Hutan', 'Savana', 'Bebatuan'],
  },
  {
    id: 'bromo-1d',
    mountain: mountains[3],
    title: 'Bromo Sunrise Trip - Half Day Adventure',
    description: 'Rasakan keindahan sunrise di Gunung Bromo tanpa perlu mendaki. Cocok untuk semua usia dengan pemandangan yang spektakuler.',
    duration: 1,
    difficulty: 'Easy',
    price: 450000,
    maxParticipants: 25,
    currentParticipants: 18,
    departureDates: ['2026-04-10', '2026-04-17', '2026-04-24', '2026-05-01', '2026-05-08', '2026-05-15'],
    itinerary: [
      {
        day: 1,
        title: 'Hari Trip: Sunrise & Volcano Adventure',
        activities: [
          'Penjemputan dari hotel (02:30)',
          'Perjalanan ke viewpoint',
          'Tiba di Penanjakan 1 untuk sunrise',
          'Menikmati pemandangan sunrise',
          'Turun ke lautan pasir',
          'Naik jeep ke view point',
          'Kembali ke hotel (10:00)',
        ],
        meals: ['Snack dan minuman hangat'],
      },
    ],
    includes: [
      'Transportasi dari Surabaya/Malang/Banyuwangi',
      'Jeep 4x4',
      'Guide lokal',
      'Tiket masuk Bromo',
      'Sarung tangan & masker',
      'Air mineral',
    ],
    excludes: [
      'Makan siang',
      'Personal expenses',
      'Tip driver',
    ],
    whatToBring: [
      'Jaket tebal',
      'Syal atau bandana',
      'Kacamata hitam',
      'Topi/beanie',
      'Kamera',
      'Sepatu tertutup',
    ],
    images: [
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
      'https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=800',
    ],
    reviews: [
      {
        id: 'rev5',
        userId: 'user5',
        userName: 'Sarah Johnson',
        userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
        rating: 5,
        comment: 'Pemandangan sunrise-nya amazing! Worth every penny. Jeep ride juga seru banget!',
        date: '2026-03-25',
        tripDate: '2026-03-22',
      },
    ],
    location: 'Taman Nasional Bromo Tengger Semeru, Jawa Timur',
    elevationGain: 300,
    terrainType: ['Lautan pasir', 'Viewpoint'],
  },
  {
    id: 'merapi-2d1n',
    mountain: mountains[4],
    title: 'Merapi Night Hiking - Kepuhargo via Selo',
    description: 'Pengalaman unik mendaki Merapi di malam hari dan menikmati sunrise dari bibir kawah. Pendakian yang penuh adrenalin!',
    duration: 2,
    difficulty: 'Hard',
    price: 1450000,
    maxParticipants: 10,
    currentParticipants: 5,
    departureDates: ['2026-04-14', '2026-04-28', '2026-05-12'],
    itinerary: [
      {
        day: 1,
        title: 'Hari 1: Night Hiking ke Summit',
        activities: [
          'Meeting point di Basecamp Selo (21:00)',
          'Briefing dan persiapan',
          'Start pendakian (22:00)',
          'Jalur via Turgo',
          'Tiba di Pasar Bubrah (02:00)',
          'Istirahat singkat',
          'Lanjut ke Summit (03:00)',
        ],
        accommodation: 'Tenda di Pasar Bubrah',
        meals: ['Snack dan minuman hangat'],
      },
      {
        day: 2,
        title: 'Hari 2: Summit - Basecamp',
        activities: [
          'Nikmati sunrise dari puncak',
          'Foto-foto dan eksplorasi kawah',
          'Turun via Selo',
          'Tiba di basecamp (10:00)',
          'Mandi dan istirahat',
          'Transfer ke Yogyakarta',
        ],
        meals: ['Sarapan', 'Makan siang'],
      },
    ],
    includes: [
      'Transportasi dari Yogyakarta',
      'Akomodasi tenda',
      'Makanan dan minuman',
      'Guide berpengalaman',
      'Tiket masuk',
      'Asuransi',
      'Peralatan camping',
    ],
    excludes: [
      'Transportasi ke meeting point',
      'Personal expenses',
    ],
    whatToBring: [
      'Sepatu hiking kuat',
      'Jaket anti air',
      'Headlamp dengan spare baterai',
      'Botrek panjang',
      'Sarung tangan climbing',
      'Topi/windbreaker',
      'Obat pribadi',
      'Kamera action',
    ],
    images: [
      'https://images.unsplash.com/photo-1578996953841-b187dbe4bc8a?w=800',
    ],
    reviews: [],
    location: 'Selo, Boyolali, Jawa Tengah',
    elevationGain: 1500,
    terrainType: ['Hutan', 'Bebatuan vulkanik', 'Kawah'],
  },
  {
    id: 'sumbing-3d2n',
    mountain: mountains[5],
    title: 'Sumbing Triangle Route - 3D2N Adventure',
    description: 'Jalur triangulasi yang paling lengkap dan menantang. Melewati 3 peak: Summit, K和要求 Saddle, dan马尾辫 Peak.',
    duration: 3,
    difficulty: 'Expert',
    price: 2450000,
    maxParticipants: 8,
    currentParticipants: 3,
    departureDates: ['2026-05-05', '2026-05-20'],
    itinerary: [
      {
        day: 1,
        title: 'Hari 1: Kali绿豆 - K要求 Saddle',
        activities: [
          'Start dari Kali绿豆 (06:00)',
          'Pendakian via Wadas',
          'Tiba di K要求 Saddle Camp (12:00)',
          'Istirahat dan makan siang',
          'Pendakian ke马尾辫 Peak (15:00)',
          'Kembali ke camp',
        ],
        accommodation: 'K要求 Saddle Camp',
        meals: ['Makan siang', 'Makan malam', 'Snack'],
      },
      {
        day: 2,
        title: 'Hari 2: Summit Attempt - Kaliwader',
        activities: [
          'Start summit (02:00)',
          'Tiba di Summit (05:00)',
          'Sunrise dari puncak tertinggi',
          'Turun via Kaliwader',
          'Tiba di Kaliwader Camp (12:00)',
        ],
        accommodation: 'Kaliwader Camp',
        meals: ['Sarapan', 'Makan siang', 'Makan malam'],
      },
      {
        day: 3,
        title: 'Hari 3: Turun ke Basecamp',
        activities: [
          'Sarapan dan packing',
          'Turun via Kaliwader',
          'Tiba di basecamp (10:00)',
          'Transfer ke kota',
        ],
        meals: ['Sarapan', 'Makan siang'],
      },
    ],
    includes: [
      'Transportasi',
      'Akomodasi tenda (2 malam)',
      'Makanan lengkap',
      '2 Guide berpengalaman',
      'Porter tambahan',
      'Tiket masuk',
      'Asuransi',
      'Peralatan camping',
    ],
    excludes: [
      'Transportasi ke basecamp',
      'Personal expenses',
    ],
    whatToBring: [
      'Sepatu hiking premium',
      'Botrek anti-slip',
      'Jaket full protection',
      'Headlamp industri',
      'Tongkat hiking',
      'First aid kit',
      'Kamera underwater',
    ],
    images: [
      'https://images.unsplash.com/photo-1585146416406-a0b9dd4e3bb9?w=800',
    ],
    reviews: [],
    location: 'Kali绿豆, Magelang, Jawa Tengah',
    elevationGain: 2300,
    terrainType: ['Hutan lebat', 'Bebatuan', 'Ridge line', 'Puncak'],
  },
];

export const polls: Poll[] = [
  {
    id: 'poll1',
    question: 'Gunung mana yang harus jadi destinasi selanjutnya untuk komunitas kita?',
    description: 'Ayo voting! Gunung mana yang kalian ingin datangi bersama komunitas kita bulan depan.',
    options: [
      { id: 'opt1', text: 'Gunung Kerinci (Sumatera)', votes: 45 },
      { id: 'opt2', text: 'Gunung Ijen (Jawa Timur)', votes: 38 },
      { id: 'opt3', text: 'Gunung Tambora (NTB)', votes: 52 },
      { id: 'opt4', text: 'Gunung Prau (Jawa Tengah)', votes: 67 },
      { id: 'opt5', text: 'Gunung Papandayan (Jawa Barat)', votes: 29 },
    ],
    createdBy: 'admin1',
    createdByName: 'Admin GunungKita',
    createdAt: '2026-03-25T08:00:00Z',
    deadline: '2026-04-20T23:59:59Z',
    isActive: true,
    totalVotes: 231,
    allowMultiple: false,
    userVotedOptions: [],
  },
  {
    id: 'poll2',
    question: 'Jenis trip apa yang lebih kalian suka?',
    description: 'Kami ingin tahu preferensi kalian untuk menentukan format trip ke depannya.',
    options: [
      { id: 'opt1', text: 'Weekend trip (2-3 hari)', votes: 89 },
      { id: 'opt2', text: 'Medium trip (4-5 hari)', votes: 67 },
      { id: 'opt3', text: 'Expedisi panjang (7+ hari)', votes: 34 },
    ],
    createdBy: 'admin1',
    createdByName: 'Admin GunungKita',
    createdAt: '2026-04-01T10:00:00Z',
    deadline: '2026-04-30T23:59:59Z',
    isActive: true,
    totalVotes: 190,
    allowMultiple: false,
    userVotedOptions: [],
  },
  {
    id: 'poll3',
    question: 'Musim pendakian favorit kalian?',
    description: 'Pilih musim yang paling kalian sukai untuk mendaki!',
    options: [
      { id: 'opt1', text: 'Musim kemarau (April-September)', votes: 156 },
      { id: 'opt2', text: 'Musim hujan (Oktober-Maret)', votes: 23 },
      { id: 'opt3', text: 'Keduanya sama saja', votes: 78 },
    ],
    createdBy: 'admin2',
    createdByName: 'Moderator Andes',
    createdAt: '2026-03-15T14:00:00Z',
    deadline: '2026-03-30T23:59:59Z',
    isActive: false,
    totalVotes: 257,
    allowMultiple: false,
    userVotedOptions: ['opt1'],
  },
];

export const users: User[] = [
  {
    id: 'user1',
    email: 'budi@example.com',
    username: 'budisan',
    displayName: 'Budi Santoso',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    bio: 'Hiking enthusiast | sudah menaklukkan 15 puncak | Based in Jakarta',
    location: 'Jakarta',
    role: 'admin',
    joinedAt: '2024-01-15T00:00:00Z',
    stats: {
      tripsCompleted: 23,
      peaksClimbed: 15,
      distanceClimbed: 450,
      totalDistance: 450,
    },
    achievements: [
      {
        id: 'ach1',
        name: 'Summit Seeker',
        description: 'Telah mencapai 10 puncak',
        icon: '🏔️',
        earnedAt: '2025-06-15',
      },
      {
        id: 'ach2',
        name: 'Trail Master',
        description: 'Mengikuti 20 trip bersama komunitas',
        icon: '🎖️',
        earnedAt: '2025-12-01',
      },
    ],
    savedTrips: ['rinjani-3d2n', 'semeru-4d3n'],
  },
  {
    id: 'user2',
    email: 'ani@example.com',
    username: 'aniwijaya',
    displayName: 'Ani Wijaya',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    bio: 'Nature lover | Photography enthusiast | First 8 peaks completed!',
    location: 'Bandung',
    role: 'moderator',
    joinedAt: '2024-03-20T00:00:00Z',
    stats: {
      tripsCompleted: 15,
      peaksClimbed: 8,
      distanceClimbed: 280,
      totalDistance: 280,
    },
    achievements: [
      {
        id: 'ach1',
        name: 'Summit Seeker',
        description: 'Telah mencapai 10 puncak',
        icon: '🏔️',
        earnedAt: '2026-01-10',
      },
    ],
    savedTrips: ['merbabu-2d1n'],
  },
  {
    id: 'user3',
    email: 'dewi@example.com',
    username: 'dewir',
    displayName: 'Dewi Rahmawati',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    bio: 'Adventure seeker | Currently training for Rinjani 🏔️',
    location: 'Surabaya',
    role: 'member',
    joinedAt: '2024-08-10T00:00:00Z',
    stats: {
      tripsCompleted: 5,
      peaksClimbed: 5,
      distanceClimbed: 120,
      totalDistance: 120,
    },
    achievements: [],
    savedTrips: ['rinjani-3d2n'],
  },
];

export const forumPosts: ForumPost[] = [
  {
    id: 'post1',
    authorId: 'user1',
    authorName: 'Budi Santoso',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    authorRole: 'admin',
    title: 'Tips Memilih Sepatu Hiking yang Tepat untuk Pemula',
    content: 'Banyak pemula yang bingung memilih sepatu hiking yang tepat. Berikut beberapa tips dari pengalaman saya:\n\n1. **Cari yang nyaman** - Try before buy! Pastikan nyaman saat dipakai berjalan.\n2. **Perhatikan sol** - Pilih sol dengan grip yang baik untuk berbagai medan.\n3. **Material** - Kulit/suede lebih tahan air, fabric lebih ringan.\n4. **Size** - Beli 1-2 size lebih besar dari sepatu biasa.\n\nSemoga membantu teman-teman yang baru mulai!',
    category: 'Tips & Tricks',
    tags: ['tips', 'persiapan', 'peralatan', 'pemula'],
    images: ['https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800'],
    createdAt: '2026-04-05T10:30:00Z',
    likes: 87,
    comments: 23,
    isPinned: true,
    userLiked: false,
  },
  {
    id: 'post2',
    authorId: 'user2',
    authorName: 'Ani Wijaya',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    authorRole: 'moderator',
    title: 'Trip Report: Pendakian Rinjani Bareng Komunitas 🌋',
    content: 'Finally bisa summit Rinjani lagi setelah 2 tahun! Trip kemarin seru banget despite weather yang kurang mendukung.\n\n**Highlight:**\n- Sunrise dari puncak yang mind-blowing\n- Pemandian air panas di Segara Anak\n- Savana di jalur pendakian\n\nTerima kasih buat tim GuideKita yang profesional!',
    category: 'Trip Report',
    tags: ['rinjani', 'trip-report', 'summit', 'komunitas'],
    images: [
      'https://images.unsplash.com/photo-1605648916361-9bc12ad6a569?w=800',
      'https://images.unsplash.com/photo-1526779259212-939e64788e3c?w=800',
    ],
    createdAt: '2026-04-03T15:45:00Z',
    likes: 124,
    comments: 45,
    isPinned: false,
    userLiked: true,
  },
  {
    id: 'post3',
    authorId: 'user4',
    authorName: 'Rizky Pratama',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    authorRole: 'member',
    title: 'Rekomendasi Camera untuk Hiking?',
    content: 'Halo para hikers!\n\nMau tanya rekomendasi camera yang oke buat dokumentasi hiking tapi tetap ringan dibawa. Saat ini pakai HP tapi pengen upgrade.\n\nBudget sekitar 5-10 juta. Prioritas:\n- Lightweight\n- Good in low light (untuk sunrise/sunset)\n- Video capability\n- Weather sealed\n\nMohon rekomendasinya ya! 🙏',
    category: 'Question',
    tags: ['kamera', 'dokumentasi', 'rekomendasi', 'gear'],
    createdAt: '2026-04-06T09:20:00Z',
    likes: 15,
    comments: 32,
    isPinned: false,
    userLiked: false,
  },
  {
    id: 'post4',
    authorId: 'user3',
    authorName: 'Dewi Rahmawati',
    authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    authorRole: 'member',
    title: 'Review: Osprey Atmos AG 65 - Worth It or Not?',
    content: 'Sudah pakai Osprey Atmos AG 65 selama 6 bulan dan 8 pendakian. Review jujur saya:\n\n**PROS:**\n- Anti-Gravity suspension system-nya nyaman banget\n- Ventilasi punggung sangat baik\n- Banyak pocket dan organization\n- Kualitas bahan premium\n\n**CONS:**\n- Pricey 💸\n- Agak berat kosong (2.1 kg)\n-不适合 untuk yang butuh carrier kecil\n\n**Verdict:** Worth it kalau sering hiking dan budget memungkinkan. Kalau baru mulai, bisa mulai dengan yang lebih affordable dulu.',
    category: 'Gear Review',
    tags: ['review', 'carrier', 'osprey', 'gear'],
    createdAt: '2026-04-01T14:00:00Z',
    likes: 56,
    comments: 18,
    isPinned: false,
    userLiked: false,
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: 'gallery1',
    tripId: 'rinjani-3d2n',
    tripName: 'Rinjani Expedition',
    image: 'https://images.unsplash.com/photo-1605648916361-9bc12ad6a569?w=800',
    caption: 'Sunrise dari puncak Rinjani - pengalaman yang tidak terlukiskan',
    author: 'Budi Santoso',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    createdAt: '2026-04-02T10:00:00Z',
    likes: 234,
    tags: ['rinjani', 'sunrise', 'puncak', 'sunset'],
  },
  {
    id: 'gallery2',
    tripId: 'merbabu-2d1n',
    tripName: 'Merbabu Starter Pack',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800',
    caption: 'Padang savana yang luas di jalur Merbabu via Campinjani',
    author: 'Rizky Pratama',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    createdAt: '2026-03-28T08:30:00Z',
    likes: 156,
    tags: ['merbabu', 'savana', 'hiking', 'alam'],
  },
  {
    id: 'gallery3',
    tripId: 'bromo-1d',
    tripName: 'Bromo Sunrise Trip',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    caption: 'Langit orange yang燃烧 saat sunrise di Bromo',
    author: 'Sarah Johnson',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
    createdAt: '2026-03-25T06:00:00Z',
    likes: 312,
    tags: ['bromo', 'sunrise', 'jeep', 'volcano'],
  },
  {
    id: 'gallery4',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
    caption: 'Momen tenang di tepi Danau Segara Anak sebelum turun',
    author: 'Ani Wijaya',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    createdAt: '2026-03-20T14:30:00Z',
    likes: 189,
    tags: ['danau', 'segara anak', 'rinjani', 'alam'],
  },
  {
    id: 'gallery5',
    image: 'https://images.unsplash.com/photo-1526779259212-939e64788e3c?w=800',
    caption: 'Camp kita di bawah langit berbintang - Sumbing trip',
    author: 'Dewi Rahmawati',
    authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    createdAt: '2026-03-15T22:00:00Z',
    likes: 278,
    tags: ['camping', 'bintang', 'sumbing', 'night'],
  },
  {
    id: 'gallery6',
    tripId: 'semeru-4d3n',
    tripName: 'Semeru Adventure',
    image: 'https://images.unsplash.com/photo-1583791196566-primer-photo?w=800',
    caption: 'Trekking through the mist at Semeru',
    author: 'Budi Santoso',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    createdAt: '2026-03-10T07:00:00Z',
    likes: 198,
    tags: ['semeru', 'mist', 'trekking', 'adventure'],
  },
];

export const currentUser: User = users[0];
